#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#Annuaires

list_directory_controller:
    path: /annuaire
    controller: App\Controller\DirectoriesController:listUser

add_directory_controller:
    path: /ajoutez-un-contact
    controller: App\Controller\DirectoriesController:addUser

details_directory_controller:
    path: /détails
    controller: App\Controller\DirectoriesController:detailsUser

update_directory_controller:
    path: /modifiez-le-contact
    controller: App\Controller\DirectoriesController:UpdateUser

delete_directory_controller:
    path: /supprimez-le-contact
    controller: App\Controller\DirectoriesController:DeleteUser

    # ANNUAIRE FICHIERS JSON

json_directory_controller1:
    path: /Annuaire_Comite-Crise
    controller: App\Controller\DirectoriesController:JsonDirectory1

json_directory_controller2:
    path: /Annuaire_Comite_Elargi
    controller: App\Controller\DirectoriesController:JsonDirectory2

json_directory_controller3:
    path: /Annuaire_Responsable_Site
    controller: App\Controller\DirectoriesController:JsonDirectory3

json_directory_controller4:
    path: /Annuaire_Numeros_Importants
    controller: App\Controller\DirectoriesController:JsonDirectory4

json_directory_controller5:
    path: /Annuaire_Non_Renseigne
    controller: App\Controller\DirectoriesController:JsonDirectory5


