#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#Annuaires

list_directory_controller:
    path: /annuaire
    controller: App\Controller\DirectoriesController:listUser

add_directory_controller:
    path: /annuaire/ajoutez
    controller: App\Controller\DirectoriesController:addUser

details_directory_controller:
    path: /annuaire/détails
    controller: App\Controller\DirectoriesController:detailsUser