#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#Annuaires

list_directory_controller:
    path: /annuaire
    controller: App\Controller\DirectoriesController:listUser

add_directory_controller:
    path: /ajoutez-un-contact
    controller: App\Controller\DirectoriesController:addUser

details_directory_controller:
    path: /détails
    controller: App\Controller\DirectoriesController:detailsUser

update_directory_controller:
    path: /modifiez-le-contact
    controller: App\Controller\DirectoriesController:UpdateUser

delete_directory_controller:
    path: /supprimez-le-contact
    controller: App\Controller\DirectoriesController:DeleteUser